# Each new term in the Fibonacci sequence is 
# generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence 
# whose values do not exceed four million, find the sum
# of the even-valued terms.

def fibonacci
  sequence = [1,2]
  new_number = 0
  sum = 0

  while new_number < 4000000
    sequence_size = sequence.length
    last_number = sequence.last
    next_to_last = sequence_size - 2

    new_number = last_number + sequence[next_to_last]

    if new_number < 4000000
      sequence << new_number
    end
  end
  
  # Find the even numbers and add them together
  sequence.each do |int|
    if int % 2 == 0
      sum += int
    end
  end

  # Return the sum
  sum
end

puts fibonacci

